/**
 * @file main.c
 * @author Trương Quốc Ánh (you@domain.com)
 * @brief Test library ver 2
 * @version 0.1
 * @date 2023-12-14
 * 
 * @copyright Copyright (c) 2023
 * 
 */
#include <stdio.h>
#include <string.h>
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/task.h"

#include "sdkconfig.h"  /** Generated by "make menuconfig" */


#include "bme.h"
#define SDA_PIN 21                     /** SDA pin: 21 */
#define SCL_PIN 22                     /** SCL pin: 22 */

void app_main()
{
    i2c_master_bme_init(SDA_PIN, SCL_PIN);
    xTaskCreate(&bme280_reader_task, "bme_280_reader_task", (1024 *2), NULL, 6, NULL);
}

